---
# Install and enable the apache service

- name: apps deploy apache
  gather_facts: false
  become: true

  tasks:
  - name: apps install apache
    yum:
      name: httpd
      state: latest

  - name: apps enable apache at boot
    service:
      name: httpd
      enabled: yes

  # Restart the apache service if any changes
  notify: apps start apache

